name: 'ALKS create role'
description: 'Create an IAM role'
inputs:
  role-type:  # id of input
    description: 'The role type to use.'
    required: true
  role-name:  # id of input
    description: 'The name of the IAM role.'
    required: true
outputs:
  arn: # id of output
    description: 'The arn of the created role's arn.'
runs:
  using: 'node12'
  main: 'index.js'